server:
  port: 1025

spring:
  application:
    name: api-getway

zuul:
  routes:
#    api-a:
#      path: /api-a/**
#      serviceId: service-provider
    api-b:
      path: /api/a/**
      serviceId: service-provider
#    api-c:
#      path: /ccc/**
#      serviceId: service-provider
  prefix: /api
#    api-b:
#      path: /api-b/**
#      serviceId: feign-consumer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
